/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Commentaries {
  book_number: number | null;
  chapter_number_from: number | null;
  chapter_number_to: number | null;
  marker: string | null;
  text: string | null;
  verse_number_from: number | null;
  verse_number_to: number | null;
}

export interface Info {
  name: string | null;
  value: string | null;
}

export interface DB {
  commentaries: Commentaries;
  info: Info;
}
