/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Books {
  book_color: string | null;
  book_number: number | null;
  long_name: string | null;
  short_name: string | null;
}

export interface Info {
  name: string | null;
  value: string | null;
}

export interface Introductions {
  book_number: number | null;
  introduction: string | null;
}

export interface Stories {
  book_number: number | null;
  chapter: number | null;
  order_if_several: number | null;
  title: string | null;
  verse: number | null;
}

export interface Verses {
  book_number: number | null;
  chapter: number | null;
  text: string | null;
  verse: number | null;
}

export interface DB {
  books: Books;
  info: Info;
  introductions: Introductions;
  stories: Stories;
  verses: Verses;
}
